<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\chart-line-bold-lightGray.png" />
    <None Remove="assets\chart-line-bold-white.png" />
    <None Remove="assets\Logo.png" />
    <None Remove="assets\note-pencil-bold-lightGray.png" />
    <None Remove="assets\note-pencil-bold-white.png" />
    <None Remove="assets\notepad-bold-lightGray.png" />
    <None Remove="assets\notepad-bold-white.png" />
    <None Remove="assets\package-bold-lightGray.png" />
    <None Remove="assets\package-bold-white.png" />
    <None Remove="assets\package-bold.png" />
    <None Remove="assets\users-four-bold-lightGray.png" />
    <None Remove="assets\users-four-bold-white.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\chart-line-bold-lightGray.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\chart-line-bold-white.png" />
    <Resource Include="assets\Logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\notepad-bold-lightGray.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\notepad-bold-white.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\package-bold-lightGray.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\package-bold-white.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\users-four-bold-lightGray.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\users-four-bold-white.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
