# ========== BUILD STAGE ==========
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln ./
COPY Jso.BookManagement.API/*.csproj Jso.BookManagement.API/
COPY Jso.BookManagement.Application/*.csproj Jso.BookManagement.Application/
COPY Jso.BookManagement.Domain/*.csproj Jso.BookManagement.Domain/
COPY Jso.BookManagement.Infrastructure/*.csproj Jso.BookManagement.Infrastructure/
RUN dotnet restore Jso.BookManagement.API/Jso.BookManagement.API.csproj

COPY . .
RUN dotnet publish Jso.BookManagement.API/Jso.BookManagement.API.csproj -c Release -o /app/publish

# ========== RUNTIME STAGE ==========
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "Jso.BookManagement.API.dll"]
